-- Auto-generated by kasyaf-ai-agent-security
-- Review policy scope before merging: this default is intentionally
-- conservative (authenticated read-only on own rows via `user_id`).
-- Adjust `USING` / `WITH CHECK` clauses to match this table's real ownership model.

-- Fix for: Table "security_logs" has RLS enabled but zero policies defined — likely blocking legitimate access or masking a misconfiguration.
ALTER TABLE public."security_logs" ENABLE ROW LEVEL SECURITY;
CREATE POLICY "kasyaf_auto_select_own_security_logs" ON public."security_logs"
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

